name: Update tokenlist.json in DragonSwap Client

on:
  push:
    branches:
      - main
    paths:
      - "tokenlist.json"

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add file to DSWAP repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          source_file: "./tokenlist.json"
          destination_branch: "develop"
          destination_repo: "dragonswap-app/dragonswap-client"
          destination_folder: "apps/dragon-swap/src/redux/tokens/"
          user_email: "marko.drakulic@nima.enterprises"
          user_name: "drakulicm"
          commit_message: "Update tokenlist.json using GitHub Actions"
