name: Update tokens.json in Another Repo

on:
  pull_request:
    types:
      - opened

jobs:
  updateTokensJson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update tokenlist.json in another repo
        run: |
          # Set up necessary variables
          SOURCE_REPO_OWNER=dragonswap-app
          SOURCE_REPO_NAME=assets
          SOURCE_FILE_PATH=tokenlist.json
          TARGET_REPO_OWNER=NIMA-Enterprises
          TARGET_REPO_NAME=dragonswap-client
          TARGET_FILE_PATH=apps/dragon-swap/tokenlist.json
          GITHUB_TOKEN=${{ secrets.GH_TOKEN }}

          # Get the content of tokenlist.json from the source repo
          SOURCE_FILE_CONTENT=$(curl -sSL -H "Authorization: token $GITHUB_TOKEN" \
            "https://raw.githubusercontent.com/$SOURCE_REPO_OWNER/$SOURCE_REPO_NAME/main/$SOURCE_FILE_PATH")

          # Update tokenlist.json in the target repo
          curl -sSL -X PUT -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"message": "Update tokenlist.json via GitHub Action", "content": "'$(echo "$SOURCE_FILE_CONTENT" | base64)'", "sha": "'$(curl -sSL -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$TARGET_REPO_OWNER/$TARGET_REPO_NAME/contents/$TARGET_FILE_PATH" | jq -r '.sha')'"}' \
            "https://api.github.com/repos/$TARGET_REPO_OWNER/$TARGET_REPO_NAME/contents/$TARGET_FILE_PATH"

        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
