name: Update tokenlist.json in DragonSwap Client

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: "NIMA-Enterprises/dragonswap-client"
          path: "apps/dragon-swap/"

      - name: Copy file
        uses: sator-imaging/Copy-to-Another-Repository@v1.0.4
        with:
          target-filepath: "tokenlist.json"
          output-branch: "main or master"
          output-repo: "dragonswap-app/assets"
          git-token: ${{ secrets.GH_TOKEN }}
